name: Build Windows EXE Qt

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 5.15.2
      - name: Configure
        run: cmake -S . -B build
      - name: Build
        run: cmake --build build --config Release
      - name: Package EXE
        run: |
          dir build\Release
      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: sticky-notes-exe
          path: build/Release/*.exe
